#!/bin/sh
###############################################################################
# dwm-windowshot
#
# This script makes a window shot (an screenshot of current selected window)
#
# -----------------------------------------------------------------------------
# DWM Scripts - wrapper for dwm/dmenu/slock
#   (C) 2007-2013 Gerardo García Peña
#   Programmed by Gerardo García Peña
#
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free
#   Software Foundation; either version 2 of the License, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#   more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc., 51
#   Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
###############################################################################

. dwm-config-read

mkdir -p "$SHOTSDIR"
FILE="$SHOTSDIR/screenshot-`date +%Y%m%d-%H.%M.%S.png`"
case "$SHOTS_BACKEND" in
gnome-screenshot)
	gnome-screenshot --area -f "$FILE"
	;;
xwd)
	xwd | xwdtopnm | pnmtopng > "$FILE"
	;;
*)
	msg "ERROR: Unknown capturing mechanism '$SHOTS_BACKEND'."
esac

if [ -e "$FILE" ]; then
	msg "windowshot left in file '$FILE'"
fi

exit 0
