#!/bin/sh
###############################################################################
# dwm-sudo
#
# This script is a wrapper for 'sudo'. It tries to use gksu, if available, or
# terminal with su/sudo if not.
#
# -----------------------------------------------------------------------------
# DWM Scripts - wrapper for dwm/dmenu/slock
#   (C) 2007-2013 Gerardo García Peña
#   Programmed by Gerardo García Peña
#
#   This program is free software; you can redistribute it and/or modify it
#   under the terms of the GNU General Public License as published by the Free
#   Software Foundation; either version 2 of the License, or (at your option)
#   any later version.
#
#   This program is distributed in the hope that it will be useful, but WITHOUT
#   ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#   FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License for
#   more details.
#
#   You should have received a copy of the GNU General Public License along
#   with this program; if not, write to the Free Software Foundation, Inc., 51
#   Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
#
###############################################################################

. dwm-config-read

if [ -z "$1" ]; then
  error "I need a command."
  exit 1
fi

if [ ! -x "$1" ]; then
  error "Path '$1' does not seem an executable program."
  exit 1
fi

# XXX TODO: check result of stat -L -c %a command
if [ "`stat -L -c "%u,%A" "$1" | cut -b 1-2,6`" = "0,s" ]; then
  msg "-------------- $1 IS A ROOT SETUID PROGRAM --------------"
  echo "$@"
else
  if which gksu > /dev/null 2>&1; then
    echo "gksu $@"
  else
    if which x-terminal-emulator > /dev/null 2>&1; then
      echo "x-terminal-emulator -e su $@"
    else
      echo "xterm -e su $@"
    fi
  fi
fi

exit 0
